ktor {
    application {
        modules = [ com.delivery.ApplicationKt.module ]
    }
    deployment {
        port = 8080
        host = "0.0.0.0"
    }
    database {
        url = "jdbc:postgresql://localhost:5432/delivery"
        driver = "org.postgresql.Driver"
        user = "postgres"
        password = "123456"
        maxPoolSize = 10
    }
    jwt {
        secret = "my-secret-key-change-me-in-production"
        issuer = "ktor-delivery"
        realm = "ktor-delivery"
    }
}